FROM {{ PLANGRID_DOCKER_REPO }}/pg-docker:master

ENV PACKER_VERSION=1.4.1 \
    PACKER_ZIPFILE_SHA256=b713ea79a6fb131e27d65ec3f2227f36932540e71820288c3c5ad770b565ecd7

RUN export PACKER_ZIPFILE=packer_${PACKER_VERSION}_linux_amd64.zip \
    && export PACKER_URL=https://releases.hashicorp.com/packer/${PACKER_VERSION}/${PACKER_ZIPFILE} \
    && wget --quiet ${PACKER_URL} \
    && echo "${PACKER_ZIPFILE_SHA256} ${PACKER_ZIPFILE}" | sha256sum --check \
    && unzip ${PACKER_ZIPFILE} \
    && install -o root -g root -m 0755 packer /usr/local/bin \
    && rm ${PACKER_ZIPFILE} packer

COPY . ./

RUN make